re update jethub-init

diff --git a/buildroot-external/board/jethome/jethub-j200/rootfs-overlay/usr/lib/jethome/jethub-init b/buildroot-external/board/jethome/jethub-j200/rootfs-overlay/usr/lib/jethome/jethub-init
--- a/buildroot-external/board/jethome/jethub-j200/rootfs-overlay/usr/lib/jethome/jethub-init
+++ b/buildroot-external/board/jethome/jethub-j200/rootfs-overlay/usr/lib/jethome/jethub-init
@@ -35,23 +35,21 @@ ENABLESYSFS=${JETHUB_SYSFS_ENABLE:-true}
 
 GPIOSET=${GPIOSET:-/usr/bin/gpioset}
 
-configure_gpiobase() {
-    GPIOBASE=""
-    GPIOCHIP=""
-    GPIOCHIPBASE=""
-
+get_gpiobase() {
+    chip="$1"
+    if [ -z "${chip}" ]; then
+        echo "Error: chip is empty"
+        exit 1
+    fi
     for gpiochipsys in /sys/class/gpio/gpiochip*/; do
         gpiochipsys=${gpiochipsys%*/}
         gpiochiptemp=$(find "$gpiochipsys"/device/gpiochip* -type d | head -n 1)
         GPIOCHIP=$(basename "$gpiochiptemp")
         GPIOBASE=$(cat "$gpiochipsys/base")
-        GPIOCHIPBASE=$(echo "$GPIOCHIP" | tr -d -c 0-9)=$GPIOBASE
+        if [ "${GPIOCHIP}" = "gpiochip${chip}" ]; then
+            echo "$GPIOBASE"
+        fi
     done
-
-    if [ -z "$GPIOBASE" ]; then
-        echo "Can not find gpiochip and base number"
-        exit 1
-    fi
 }
 
 gpio_set() {
@@ -59,7 +57,7 @@ gpio_set() {
     GPIOL=$2
     VALUE=$3
     LOW=$4
-    base=$(echo "$GPIOCHIPBASE" | grep -o "${gpiochip}=[0-9]*" | cut -d= -f2)
+    base=$(get_gpiobase "${gpiochip}")
     echo "$0: GPIOSET: gpiochip=$gpiochip line=$GPIOL val=$VALUE low=$LOW base=$base"
 
     if [ "$ENABLESYSFS" = "true" ]; then
@@ -124,8 +122,6 @@ unexport_sysfs
 
 if [ "$ENABLESYSFS" = "true" ]; then
     echo "$0: Configure GPIOs as sysfs ..."
-
-    configure_gpiobase
 
     # Discrete inputs: 1, 2, 3
     configure_gpio 2  8 ${GPIO_DIRECTION_INPUT} ${GPIO_ACTIVE_HIGH}
